version: '3.8'

services:
  db_user:
    image: mariadb:11.0.2
    container_name: user_db
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: mediscreen_patient
      MYSQL_USER: mediscreen
      MYSQL_PASSWORD: M3d1Scr33n
    ports:
      - 3306:3306
    volumes:
      - dbpatient_mediscreen:/var/lib/mysql

volumes:
  dbpatient_mediscreen: